data_publisher:
    ros__parameters:
        K: 1.0
        Td: 1000000.0
        Ti: 0.0
        publish_period: 500.0
        control_period: 60.0
        frame_rate: 100.0
        line_detect_method: 1.0
        points_number: 6.0
        resolution_factor: 0.5
