#all parameters must be double!
data_publisher:
    ros__parameters:
        K: 0.35
        Ti: 50.0
        Td: 0.1
        const_vel: 140.0
        vel_up_lim: 70.0
        vel_down_lim: -70.0

        line_detect_method: 1.0 # 1-contour method, 2-center method - not implemented yet, mode no 1 is used
        points_number: 6.0 # for mode no 2 - not implemented yet
        up_roi_boundary: 0.167 # for mode no 1
        down_roi_boundary: 0.833 # for mode no 1
        resolution_factor: 0.5
        detection_threshold: 50.0

        publish_period: 40.0 # ms - give integer in double format 
        detection_period: 40.0 # ms
        control_period: 40.0 # ms
